ALTER TABLE plank_tokens
ADD COLUMN session_id CHAR(36) NOT NULL,
ADD COLUMN user_agent VARCHAR(512) DEFAULT NULL,
ADD COLUMN ip_address VARCHAR(45) DEFAULT NULL,
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE plank_tokens DROP PRIMARY KEY;

ALTER TABLE plank_tokens
ADD COLUMN id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
